### ISSUE TITLE
Birthday is not upated if keyboard is used to enter it, and Enter is not pressen afterwards!

### ISSUE THREAD

**Issue by commi** [jfischer23/birthday_wish_generator#1]
i want my money back!

**Comment by commi** [comment]
suggestion: try a listener for the controls' `focused`-property or in the controls `editor`s `text`-property, and update the `value`-prop there.

**Comment by jfischer23** [comment]
Solved problem with the editors text property (see commit 082799cbaa59b0071386cc318ab230d88f2d9d00). Thanks for the advise :)
